name: Deploy Site
on:
  push:
    branches:
      - auto_deploy
jobs:
  build-and-deploy:
    #concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v4
          with:
            persist-credentials: false
        - name: Install and Build 🔧
          run: |
            cd VerbApp
            npm install
            ionic build --prod  
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v3
          with:
            folder: VerbApp/www
            token:  ${{ github.token }}
